
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Navbar from '../../layout/Navbar';
import Footer from '../../layout/Footer';
import { useDisputeLettersData, Letter } from './hooks/useDisputeLettersData';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { FileText, AlertTriangle, RefreshCw, RotateCw } from 'lucide-react';
import { Profile } from '@/lib/supabase/client';
import { useToast } from '@/hooks/use-toast';

// Import existing components
import DisputeLettersList from './DisputeLettersList';  
import DisputeLetterViewer from './DisputeLetterViewer';
import DisputeLetterHeader from './DisputeLetterHeader';

interface DisputeLettersPageProps {
  testMode?: boolean;
  requirePayment?: boolean;
}

const DisputeLettersPage: React.FC<DisputeLettersPageProps> = ({ testMode = false, requirePayment = false }) => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const { 
    letters, 
    setLetters, 
    addLetter, 
    selectedLetter, 
    setSelectedLetter, 
    isLoading,
    saveLetter,
    profile
  } = useDisputeLettersData(testMode);
  
  // States for letter generation and loading management
  const [isGenerating, setIsGenerating] = useState(false);
  const [letterLoadAttempts, setLetterLoadAttempts] = useState(0);
  const [loadingTimeout, setLoadingTimeout] = useState(false);
  const [forceReload, setForceReload] = useState(false);
  
  // Handle loading timeout - show message if taking too long
  useEffect(() => {
    // If still loading after 5 seconds, show timeout message
    const timeoutId = setTimeout(() => {
      if (isLoading) {
        setLoadingTimeout(true);
        console.log("Loading timeout reached, showing error options");
        
        // Force transition from loading to empty state if still loading after 10 seconds
        const forceTransitionTimeout = setTimeout(() => {
          if (isLoading) {
            console.log("Forcing transition from loading to empty state");
            setForceReload(true);
            
            // Show toast notification
            toast({
              title: "Loading Issue Detected",
              description: "We've reset the loading state. Please try creating a new letter.",
            });
          }
        }, 5000); // Additional 5 seconds before forcing state transition
        
        return () => clearTimeout(forceTransitionTimeout);
      }
    }, 5000); // Initial 5 seconds before showing timeout message
    
    return () => clearTimeout(timeoutId);
  }, [isLoading, toast]);
  
  // Handler for generating new dispute letters
  const handleGenerateDispute = async (disputeData: any) => {
    setIsGenerating(true);
    try {
      // Add the letter once generated
      addLetter(disputeData);
    } finally {
      setIsGenerating(false);
    }
  };
  
  const [navHeight, setNavHeight] = useState<number>(0);
  
  // Effect to measure navbar height
  useEffect(() => {
    const navbar = document.getElementById('main-navbar');
    if (navbar) {
      setNavHeight(navbar.offsetHeight);
    }
  }, []);
  
  // Create letter from issues found in the credit report
  const handleCreateLetterFromIssues = () => {
    navigate('/upload-report' + (testMode ? '?testMode=true' : ''));
  };
  
  // Reset session storage and retry loading
  const handleResetAndRetry = () => {
    // Clear session storage related to letters
    sessionStorage.removeItem('pendingDisputeLetter');
    sessionStorage.removeItem('generatedDisputeLetters');
    sessionStorage.removeItem('autoGeneratedLetter');
    sessionStorage.removeItem('forceLettersReload');
    sessionStorage.removeItem('navigationInProgress');
    
    // Show retry toast
    toast({
      title: "Retrying",
      description: "Resetting data and trying again...",
    });
    
    // Redirect to upload report page to start fresh
    setTimeout(() => {
      navigate('/upload-report');
    }, 1000);
  };

  // Force reload the page
  const handleForceReload = () => {
    toast({
      title: "Reloading Page",
      description: "Refreshing the dispute letters page...",
    });
    
    // Force hard reload
    window.location.reload();
  };

  // Function to handle letter selection that converts the type properly
  const handleSelectLetter = (letter: Letter) => {
    setSelectedLetter(letter);
  };
  
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Navbar />
      
      <main 
        className="flex-grow pt-24 pb-20"
        style={{ marginTop: navHeight > 0 ? `${navHeight}px` : undefined }}
      >
        <div className="container mx-auto px-4 md:px-6">
          <DisputeLetterHeader testMode={testMode} />
          
          {/* Loading Timeout Error Message */}
          {loadingTimeout && isLoading && (
            <Alert className="mb-8 border-destructive bg-destructive/10">
              <AlertTriangle className="h-5 w-5 text-destructive" />
              <AlertTitle className="text-foreground font-semibold">
                Taking Too Long to Load
              </AlertTitle>
              <AlertDescription className="text-foreground/90">
                Your dispute letters are taking too long to load. This might be due to a temporary issue.
              </AlertDescription>
              <div className="flex flex-wrap gap-4 mt-4">
                <Button 
                  variant="outline" 
                  className="bg-background border-border hover:bg-accent flex items-center gap-2"
                  onClick={handleForceReload}
                >
                  <RotateCw size={16} />
                  Reload Page
                </Button>
                <Button 
                  variant="destructive" 
                  onClick={handleResetAndRetry}
                >
                  Reset & Create New Letter
                </Button>
              </div>
            </Alert>
          )}
          
          {(forceReload || (!isLoading && letterLoadAttempts >= 3 && letters.length === 0)) && (
            <Alert className="mb-8 border-amber-300 bg-amber-50/50 dark:bg-amber-900/30 dark:border-amber-800/50">
              <FileText className="h-5 w-5 text-amber-600 dark:text-amber-500" />
              <AlertTitle className="text-amber-800 dark:text-amber-400 font-semibold">
                No Dispute Letters Found
              </AlertTitle>
              <AlertDescription className="text-amber-700 dark:text-amber-300">
                You don't have any dispute letters yet. To generate dispute letters based on your credit report, 
                please upload and analyze your credit report first.
              </AlertDescription>
              <Button 
                variant="outline" 
                className="mt-3 bg-background dark:bg-background border-amber-300 dark:border-amber-800/50 text-amber-700 dark:text-amber-300 hover:bg-amber-100 dark:hover:bg-amber-900/50"
                onClick={handleCreateLetterFromIssues}
              >
                <FileText className="mr-2 h-4 w-4" />
                Upload Credit Report
              </Button>
            </Alert>
          )}
          
          {isLoading && !forceReload && (
            <Alert className="mb-8 border-primary/30 bg-primary/5">
              <AlertTitle className="text-foreground font-semibold">
                Loading Letters
              </AlertTitle>
              <AlertDescription className="text-foreground/80">
                Please wait while we load your dispute letters...
                {loadingTimeout && 
                  " This is taking longer than expected. You can continue waiting or try the options above."}
              </AlertDescription>
              {!loadingTimeout && (
                <div className="w-full flex justify-center mt-4">
                  <div className="w-8 h-8 border-4 border-t-primary border-primary/20 rounded-full animate-spin"></div>
                </div>
              )}
            </Alert>
          )}
          
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <div className="lg:col-span-1">
              <DisputeLettersList 
                letters={letters}
                selectedLetter={selectedLetter}
                onSelectLetter={handleSelectLetter}
                isLoading={isLoading && !forceReload}
                onCreateLetter={handleCreateLetterFromIssues}
                testMode={testMode}
                userProfile={profile as Profile}
              />
            </div>
            
            <div className="lg:col-span-2">
              <DisputeLetterViewer 
                letter={selectedLetter}
                isLoading={isLoading && !forceReload}
                testMode={testMode}
                userProfile={profile as Profile}
              />
            </div>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default DisputeLettersPage;
