
import React from 'react';
import { CheckCircle, FileText } from 'lucide-react';

interface FCRAComplianceSectionProps {
  onCreateLetter: () => void;
}

const FCRAComplianceSection: React.FC<FCRAComplianceSectionProps> = ({ onCreateLetter }) => {
  return (
    <div className="bg-white dark:bg-credify-navy/20 rounded-xl shadow-soft border border-gray-100 dark:border-gray-700/30 p-6 md:p-8">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-10 items-center">
        <div>
          <h2 className="text-2xl font-bold text-credify-navy dark:text-white mb-4">
            FCRA-Compliant Dispute Letters
          </h2>
          
          <p className="text-credify-navy-light dark:text-white/70 mb-6">
            All letters generated by Credify A.I. are fully compliant with the Fair Credit Reporting Act (FCRA) and cite relevant legal sections to strengthen your disputes.
          </p>
          
          <ul className="space-y-3 mb-6">
            <li className="flex items-start gap-2">
              <CheckCircle className="text-credify-teal mt-0.5 flex-shrink-0" size={18} />
              <span className="text-credify-navy-light dark:text-white/70">
                <strong className="text-credify-navy dark:text-white">Legally sound language</strong> that clearly states your rights under the FCRA
              </span>
            </li>
            <li className="flex items-start gap-2">
              <CheckCircle className="text-credify-teal mt-0.5 flex-shrink-0" size={18} />
              <span className="text-credify-navy-light dark:text-white/70">
                <strong className="text-credify-navy dark:text-white">Specific citations</strong> to relevant FCRA sections applicable to your situation
              </span>
            </li>
            <li className="flex items-start gap-2">
              <CheckCircle className="text-credify-teal mt-0.5 flex-shrink-0" size={18} />
              <span className="text-credify-navy-light dark:text-white/70">
                <strong className="text-credify-navy dark:text-white">Clear timelines</strong> for credit bureaus to investigate and respond to your dispute
              </span>
            </li>
          </ul>
          
          <button
            onClick={onCreateLetter}
            className="text-credify-teal hover:text-credify-teal-dark dark:hover:text-credify-teal-light font-medium transition-colors"
          >
            Create your FCRA-compliant letter →
          </button>
        </div>
        
        <div className="bg-gray-100 dark:bg-gray-800/30 p-6 rounded-lg">
          <div className="p-4 bg-white dark:bg-credify-navy/60 rounded border border-gray-200 dark:border-gray-700/50 shadow-sm">
            <div className="flex items-center gap-3 border-b border-gray-200 dark:border-gray-700/30 pb-4 mb-4">
              <FileText className="text-credify-teal" size={24} />
              <div>
                <h3 className="font-medium text-credify-navy dark:text-white">Sample Dispute Letter</h3>
                <p className="text-xs text-credify-navy-light dark:text-white/70">Section 611 FCRA Dispute</p>
              </div>
            </div>
            
            <div className="space-y-2 text-sm text-credify-navy-light dark:text-white/70">
              <p>[Your Name]</p>
              <p>[Your Address]</p>
              <p>[City, State ZIP]</p>
              <p className="pt-2">[Date]</p>
              <p className="pt-2">[Credit Bureau Name]</p>
              <p>[Bureau Address]</p>
              <p>[City, State ZIP]</p>
              
              <p className="pt-3 text-credify-navy dark:text-white">RE: Dispute of Inaccurate Information</p>
              
              <p className="pt-3">To Whom It May Concern:</p>
              
              <p className="pt-2">I am writing to dispute inaccurate information in my credit report. I have identified the following item(s) that should be corrected:</p>
              
              <p className="pt-2 italic text-credify-navy dark:text-white font-medium">
                [Description of disputed item, account number, and reason for dispute]
              </p>
              
              <p className="pt-2">According to Section 611 of the Fair Credit Reporting Act (FCRA), you are required to conduct a reasonable investigation into this matter...</p>
              
              <p className="text-center pt-2 italic">[Letter continues...]</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FCRAComplianceSection;
