
import { MutableRefObject, useCallback } from 'react';
import { CreditReportData, IdentifiedIssue } from '@/utils/creditReport/types';
import { handleAnalysisComplete } from '@/components/disputes/uploader/handlers/analysisHandler';
import { useToast } from '@/hooks/use-toast';

// Helper function to yield control back to the browser
const yieldToMain = () => new Promise(resolve => setTimeout(resolve, 0));

export const useReportAnalysis = (
  uploadedFile: File | null,
  setReportData: (data: CreditReportData) => void,
  setIssues: (issues: IdentifiedIssue[]) => void,
  setLetterGenerated: (generated: boolean) => void,
  setAnalysisError: (error: string | null) => void,
  setAnalyzing: (analyzing: boolean) => void,
  setAnalyzed: (analyzed: boolean) => void,
  analysisCompleted: MutableRefObject<boolean>
) => {
  const { toast } = useToast();
  
  // Enhanced startAnalysis with better handling to prevent browser unresponsive errors
  const startAnalysis = useCallback(async () => {
    if (uploadedFile) {
      console.log("Starting analysis of uploaded file:", uploadedFile.name);
      setAnalyzing(true);
      setAnalysisError(null);
      
      // Clear any existing letter data to prevent confusion
      sessionStorage.removeItem('pendingDisputeLetter');
      sessionStorage.removeItem('generatedDisputeLetters');
      sessionStorage.removeItem('autoGeneratedLetter');
      sessionStorage.removeItem('shouldNavigateToLetters');
      
      // Create a compatible toast object for the handler
      const toastObject = {
        toast: toast,
        dismiss: () => {},
        toasts: []
      };
      
      try {
        // Use setTimeout to allow the browser to update UI before starting analysis
        setTimeout(async () => {
          try {
            // Yield control once before starting CPU-intensive task
            await yieldToMain();
            
            // Set a backup timeout to force completion if the analysis gets stuck
            const analysisBackupTimeout = setTimeout(() => {
              if (!analysisCompleted.current) {
                console.log("Analysis backup timeout reached - forcing completion");
                onAnalysisComplete();
              }
            }, 25000); // 25 second backup timeout
            
            // Updated to pass the props object that handleAnalysisComplete expects
            await handleAnalysisComplete({
              uploadedFile,
              setReportData,
              setIssues,
              setLetterGenerated,
              setAnalysisError,
              setAnalyzing,
              setAnalyzed,
              toast: toastObject,
              testMode: false // Always use real mode, no test mode with per-letter payments
            });
            
            clearTimeout(analysisBackupTimeout);
            
            // Store flag for letter generation after analysis
            sessionStorage.setItem('reportAnalyzed', 'true');
            sessionStorage.setItem('reportReadyForLetters', 'true');
          } catch (err) {
            console.error("Error in analysis:", err);
            setAnalysisError(err instanceof Error ? err.message : "Unknown error occurred");
            setAnalyzing(false);
            
            toast({
              title: "Analysis Error",
              description: err instanceof Error ? err.message : "Unknown error analyzing your report",
              variant: "destructive"
            });
          }
        }, 100);
      } catch (error) {
        console.error("Error initiating analysis:", error);
        setAnalysisError(error instanceof Error ? error.message : "Unknown error occurred");
        setAnalyzing(false);
        
        toast({
          title: "Analysis Error",
          description: "Failed to start credit report analysis",
          variant: "destructive"
        });
      }
    } else {
      console.error("Attempted to start analysis without an uploaded file");
      setAnalysisError("No file was uploaded");
      
      toast({
        title: "Missing File",
        description: "Please upload a credit report file first",
        variant: "destructive"
      });
    }
  }, [uploadedFile, setReportData, setIssues, setLetterGenerated, setAnalysisError, setAnalyzing, setAnalyzed, toast, analysisCompleted]);

  const onAnalysisComplete = useCallback(() => {
    // Mark analysis as complete
    console.log("Analysis marked as complete");
    analysisCompleted.current = true;
    setAnalyzed(true);
    setAnalyzing(false);
    
    // Set flag for automatic letter generation
    sessionStorage.setItem('analysisComplete', 'true');
    sessionStorage.setItem('reportReadyForLetters', 'true');
  }, [setAnalyzed, setAnalyzing, analysisCompleted]);

  return {
    onAnalysisComplete,
    startAnalysis
  };
};
