
import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useToast } from '@/hooks/use-toast';

export const useReportNavigation = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  
  // Set up navigation listener for analysis completion
  useEffect(() => {
    // Create a MutationObserver to watch for the special console log
    const originalConsoleLog = console.log;
    console.log = function() {
      // Call the original console.log
      originalConsoleLog.apply(console, arguments);
      
      // Check if this is our special navigation trigger message
      if (arguments[0] === "ANALYSIS_COMPLETE_READY_FOR_NAVIGATION") {
        originalConsoleLog("Detected navigation trigger - redirecting to dispute letters page");
        setTimeout(() => {
          navigateToDisputeLetters();
        }, 500);
      }
    };
    
    return () => {
      // Restore original console.log when component unmounts
      console.log = originalConsoleLog;
    };
  }, [navigate]);

  // Navigate to dispute letters page with more forceful approach
  const navigateToDisputeLetters = () => {
    console.log("Forcefully navigating to dispute letters page");
    
    // Verify letters exist before navigating
    const pendingLetter = sessionStorage.getItem('pendingDisputeLetter');
    const forceRegenerate = sessionStorage.getItem('forceRegenerateFullLetter');
    
    // If no letter exists or we need to regenerate, check if we have issue details to create one
    if (!pendingLetter || forceRegenerate === 'true') {
      const disputeDetails = sessionStorage.getItem('currentDisputeDetails');
      
      if (disputeDetails) {
        console.log("Creating comprehensive letter before navigation");
        sessionStorage.removeItem('forceRegenerateFullLetter');
        
        try {
          // Create a properly formatted letter with real content
          const details = JSON.parse(disputeDetails);
          const currentDate = new Date().toLocaleDateString('en-US', {
            year: 'numeric', month: 'long', day: 'numeric'
          });
          
          // Generate a more comprehensive letter
          const letterContent = generateDetailedDisputeLetter(details, currentDate);
          
          const letter = {
            id: Date.now(),
            title: `${details.title} (${details.accountName || 'Unknown Account'})`,
            bureau: details.bureau || "Experian",
            recipient: details.bureau || "Experian",
            accountName: details.accountName || "Unknown Account",
            accountNumber: details.accountNumber || "",
            errorType: details.title,
            explanation: details.description,
            letterContent: letterContent,
            content: letterContent,
            status: 'draft',
            createdAt: new Date().toLocaleDateString('en-US', { 
              month: 'short', day: 'numeric', year: 'numeric' 
            }),
            bureaus: [details.bureau || "Experian"],
            laws: details.laws || ["FCRA § 611"],
            timestamp: new Date().toISOString()
          };
          
          // Store the letter
          sessionStorage.setItem('pendingDisputeLetter', JSON.stringify(letter));
          sessionStorage.setItem('generatedDisputeLetters', JSON.stringify([letter]));
          sessionStorage.setItem('autoGeneratedLetter', 'true');
          console.log("Created and stored comprehensive letter before navigation");
        } catch (e) {
          console.error("Error creating comprehensive letter:", e);
        }
      }
    }
    
    // Set flag to force reload on letters page
    sessionStorage.setItem('forceLettersReload', 'true');
    
    // Force navigation by updating the window location
    // This is more reliable than using React Router for this critical navigation
    window.location.href = '/dispute-letters';
  };
  
  // Helper function to generate a detailed, realistic dispute letter
  const generateDetailedDisputeLetter = (details: any, currentDate: string) => {
    const addressMap: Record<string, string> = {
      'experian': 'Experian\nP.O. Box 4500\nAllen, TX 75013',
      'equifax': 'Equifax Information Services LLC\nP.O. Box 740256\nAtlanta, GA 30374',
      'transunion': 'TransUnion LLC\nConsumer Dispute Center\nP.O. Box 2000\nChester, PA 19016'
    };
    
    const bureau = (details.bureau || 'experian').toLowerCase();
    const bureauAddress = addressMap[bureau] || addressMap['experian'];
    
    // Create a comprehensive letter with detailed FCRA language based on the dispute type
    let fcraLanguage = "";
    
    // Add specialized language based on issue type
    if (details.title.toLowerCase().includes("late") || details.title.toLowerCase().includes("payment")) {
      fcraLanguage = `Under the Fair Credit Reporting Act (FCRA) Section 623(a)(3), furnishers must investigate and correct any inaccurate payment information when notified of a dispute. The reported late payment information is inaccurate and damaging to my credit profile.`;
    } else if (details.title.toLowerCase().includes("inquiry")) {
      fcraLanguage = `Under FCRA Section 604(a), inquiries can only be made with permissible purpose and consumer authorization. I have no record of providing authorization for this inquiry, and it should be removed from my report.`;
    } else if (details.title.toLowerCase().includes("account") || details.title.toLowerCase().includes("not mine")) {
      fcraLanguage = `According to FCRA Section 611(a), upon receiving notice of dispute, credit reporting agencies must conduct a reasonable investigation. This account appears to contain errors requiring correction or does not belong to me.`;
    } else {
      fcraLanguage = `Under the Fair Credit Reporting Act § 611 (FCRA § 611), you are required to conduct a reasonable investigation into this matter and remove or correct any information that cannot be verified.`;
    }
    
    // Get specific laws text from the details
    const lawsText = details.laws ? details.laws.join('\n') : 'FCRA § 611 (Fair Credit Reporting Act)';
    
    return `${currentDate}

${bureauAddress}

Re: Dispute of Inaccurate Information in Credit Report

To Whom It May Concern:

I am writing to dispute the following information in my credit report. I have identified errors related to the following account:

Account Name: ${details.accountName}
${details.accountNumber ? `Account Number: ${details.accountNumber}` : ''}
Issue Type: ${details.title}

Description of the error:
${details.description}

${fcraLanguage}

This matter requires immediate attention as it is negatively impacting my credit score and financial standing. I am exercising my rights under the Fair Credit Reporting Act (FCRA) to have this information investigated and corrected.

Please conduct a thorough investigation of this matter and delete or correct the disputed information. According to FCRA Section 611(a)(1), your agency is required to complete this investigation within 30 days of receiving this dispute.

Additionally, please send me notification of your investigation results and an updated copy of my credit report if changes are made. If any information in the disputed item is found to be inaccurate or cannot be verified, please delete it and notify all parties who have received my report in the past six months of this change.

Applicable Laws:
${lawsText}

Thank you for your prompt attention to this matter.

Sincerely,
[YOUR NAME]

[YOUR ADDRESS]
[CITY, STATE ZIP]

Enclosures:
- Copy of Driver's License
- Copy of Social Security Card
`;
  };

  return {
    navigateToDisputeLetters,
    navigate,
    toast
  };
};
