import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { CreditReportAccount } from '@/utils/creditReportParser';
import { useReportUploadState } from './report-upload/useReportUploadState';
import { useReportStorage } from './report-upload/useReportStorage';
import { useReportNavigation } from './report-upload/useReportNavigation';
import { useReportAnalysis } from './report-upload/useReportAnalysis';

export const useReportUpload = () => {
  // Compose the smaller hooks
  const {
    fileUploaded,
    fileName,
    fileSize,
    uploadedFile,
    analyzing,
    setAnalyzing,
    analyzed,
    setAnalyzed,
    analysisError,
    setAnalysisError,
    reportData,
    setReportData,
    issues,
    setIssues,
    letterGenerated,
    setLetterGenerated,
    analysisInProgress,
    analysisCompleted,
    handleFile,
    resetUpload
  } = useReportUploadState();

  const { 
    checkPendingLetters, 
    clearPendingLetters, 
    storeForDispute 
  } = useReportStorage();

  const { 
    navigateToDisputeLetters, 
    navigate, 
    toast 
  } = useReportNavigation();

  const {
    onAnalysisComplete,
    startAnalysis
  } = useReportAnalysis(
    uploadedFile,
    setReportData,
    setIssues,
    setLetterGenerated,
    setAnalysisError,
    setAnalyzing,
    setAnalyzed,
    analysisCompleted
  );

  // Add the letter generation effect with stronger navigation logic
  useEffect(() => {
    if (letterGenerated) {
      console.log("Letter has been generated, checking storage before navigation");
      
      // Verify that we have letters in storage
      const pendingLetter = sessionStorage.getItem('pendingDisputeLetter');
      const generatedLetters = sessionStorage.getItem('generatedDisputeLetters');
      
      if (pendingLetter || generatedLetters) {
        console.log("Letters found in storage, navigating to dispute letters page");
        // Set flag to force reload on letters page
        sessionStorage.setItem('forceLettersReload', 'true');
        
        // Add a longer delay to ensure storage operations complete
        const timer = setTimeout(() => {
          console.log("Executing navigation to dispute-letters");
          navigate('/dispute-letters');
        }, 1500); // Increased delay to 1.5 seconds
        
        return () => clearTimeout(timer);
      } else {
        console.error("Letter generated flag is true but no letters found in storage");
        
        // Try to set letterGenerated to false to allow the user to try again
        setLetterGenerated(false);
        
        // Use the toast function correctly as a function call with an object parameter
        toast({
          title: "Letter Storage Error",
          description: "Letters were generated but couldn't be saved. Please try again.",
          variant: "destructive"
        });
      }
    }
  }, [letterGenerated, navigate, toast, setLetterGenerated]);

  // Handle generate dispute (combines storeForDispute and navigation)
  const handleGenerateDispute = (account?: CreditReportAccount) => {
    if (reportData) {
      // Clear existing letters first to avoid conflicts
      sessionStorage.removeItem('pendingDisputeLetter');
      sessionStorage.removeItem('generatedDisputeLetters');
      sessionStorage.removeItem('autoGeneratedLetter');
      sessionStorage.removeItem('forceLettersReload');
      
      storeForDispute(reportData, account);
      
      // Add delay to ensure storage operations complete before navigation
      setTimeout(() => {
        navigateToDisputeLetters();
      }, 300);
    }
  };

  // Debug logging for state changes
  console.log("UploadReport state:", { 
    fileUploaded, 
    analyzing, 
    analyzed, 
    letterGenerated,
    analysisInProgress: analysisInProgress.current,
    analysisCompleted: analysisCompleted.current,
  });

  return {
    fileUploaded,
    analyzing,
    analyzed,
    fileName,
    fileSize,
    reportData,
    uploadedFile,
    issues,
    letterGenerated,
    analysisError,
    resetUpload,
    startAnalysis,
    handleGenerateDispute,
    onAnalysisComplete,
    handleFile,
    clearPendingLetters
  };
};
