
import { useCallback } from 'react';
import { CreditReportData, CreditReportAccount } from '@/utils/creditReport/types';

/**
 * Hook to manage storage of credit report data for dispute generation
 */
export const useReportStorage = () => {
  /**
   * Store credit report and selected account for dispute generation
   */
  const storeForDispute = useCallback((
    reportData: CreditReportData,
    selectedAccount: CreditReportAccount | null = null
  ): boolean => {
    try {
      console.log("Storing credit report data for dispute generation");
      
      // CRITICAL: Clear any existing letters first to prevent reusing old letters
      clearAllLetterData();
      
      // Store the full report data
      sessionStorage.setItem('creditReportData', JSON.stringify(reportData));
      
      // Store the selected account if provided
      if (selectedAccount) {
        sessionStorage.setItem('selectedDisputeAccount', JSON.stringify(selectedAccount));
        console.log("Selected account stored:", selectedAccount.accountName);
      }
      
      // Note that a report is ready for letter generation
      sessionStorage.setItem('reportReadyForLetters', 'true');
      
      return true;
    } catch (error) {
      console.error("Error storing report data:", error);
      return false;
    }
  }, []);
  
  /**
   * Check for pending dispute letters
   * This returns boolean (not sample data)
   */
  const checkPendingLetters = useCallback((): boolean => {
    try {
      // Check for any pending letters
      const hasPending = sessionStorage.getItem('pendingDisputeLetter') !== null ||
                        sessionStorage.getItem('generatedDisputeLetters') !== null ||
                        sessionStorage.getItem('autoGeneratedLetter') !== null;
      
      return hasPending;
    } catch (error) {
      return false;
    }
  }, []);
  
  /**
   * Clear stored report data
   */
  const clearStoredReport = useCallback((): void => {
    sessionStorage.removeItem('creditReportData');
    sessionStorage.removeItem('selectedDisputeAccount');
    sessionStorage.removeItem('reportReadyForLetters');
    clearAllLetterData(); // Also clear all letter data
    console.log("Cleared stored report data and all letter data");
  }, []);
  
  /**
   * Load stored credit report data
   */
  const loadStoredReport = useCallback((): CreditReportData | null => {
    try {
      const storedData = sessionStorage.getItem('creditReportData');
      if (!storedData) return null;
      
      return JSON.parse(storedData);
    } catch (error) {
      console.error("Error loading stored report data:", error);
      return null;
    }
  }, []);
  
  /**
   * Clear all letter data from session storage
   * This is critical to prevent reusing old letters
   */
  const clearAllLetterData = useCallback((): void => {
    // Clear ALL letter-related storage items
    sessionStorage.removeItem('pendingDisputeLetter');
    sessionStorage.removeItem('generatedDisputeLetters');
    sessionStorage.removeItem('autoGeneratedLetter');
    sessionStorage.removeItem('hasDisputeLetters');
    sessionStorage.removeItem('forceLettersReload');
    sessionStorage.removeItem('letterTemplate');
    sessionStorage.removeItem('sampleLetters');
    sessionStorage.removeItem('fallbackLetterUsed');
    console.log("Cleared ALL letter data from storage");
  }, []);
  
  return {
    storeForDispute,
    checkPendingLetters,
    clearStoredReport,
    loadStoredReport,
    clearAllLetterData
  };
};
