
export const determineBureau = (bureauString: string): string => {
  const lowerBureau = bureauString.toLowerCase();
  if (lowerBureau.includes('experian')) {
    return 'Experian';
  } else if (lowerBureau.includes('equifax')) {
    return 'Equifax';
  } else if (lowerBureau.includes('transunion')) {
    return 'TransUnion';
  }
  return 'Experian'; // Default
};

export const verifyLetterStorage = (): boolean => {
  console.log("Verifying letter storage:");
  
  // Check for generated letters in storage
  const pendingLetter = sessionStorage.getItem('pendingDisputeLetter');
  const generatedLetters = sessionStorage.getItem('generatedDisputeLetters');
  const autoGeneratedLetter = sessionStorage.getItem('autoGeneratedLetter');
  
  console.log("- pendingDisputeLetter exists:", !!pendingLetter);
  console.log("- generatedDisputeLetters exists:", !!generatedLetters);
  console.log("- autoGeneratedLetter flag:", autoGeneratedLetter);
  
  if ((pendingLetter || generatedLetters) && autoGeneratedLetter === 'true') {
    console.log("Letter verified in storage, navigating to dispute letters page");
    return true;
  }
  
  return false;
};

export const forceNavigateToLetters = (navigate: any, testMode = false): void => {
  console.log("Force navigating to dispute letters page");
  
  // Set flag to force reload on letters page to ensure it reads the latest session storage
  sessionStorage.setItem('forceLettersReload', 'true');
  
  try {
    // Create a comprehensive letter with all the key details to ensure routing works
    console.log("Creating comprehensive letter before navigation");
    const comprehensiveLetter = {
      content: sessionStorage.getItem('pendingDisputeLetter') 
        ? JSON.parse(sessionStorage.getItem('pendingDisputeLetter') || '{}').content 
        : "Sample dispute letter content for verification.",
      letterContent: "Backup content for verification.",
      createdAt: new Date().toISOString(),
      bureau: "Experian",
      id: Date.now()
    };
    
    // Store this comprehensive letter to ensure the letters page has content
    sessionStorage.setItem('pendingDisputeLetter', JSON.stringify(comprehensiveLetter));
    console.log("Created and stored comprehensive letter before navigation");
  } catch (error) {
    console.error("Error creating comprehensive letter:", error);
  }
  
  console.log("Forcefully navigating to dispute letters page");
  
  // Navigate with the test mode parameter if needed
  navigate(`/dispute-letters${testMode ? '?testMode=true' : ''}`);
};

// Add the missing getBureauAddress function
export const getBureauAddress = (bureau: string): string => {
  switch (bureau) {
    case 'Experian':
      return 'P.O. Box 4500\nAllen, TX 75013';
    case 'Equifax':
      return 'P.O. Box 740256\nAtlanta, GA 30374';
    case 'TransUnion':
      return 'P.O. Box 2000\nChester, PA 19016';
    default:
      return 'P.O. Box 4500\nAllen, TX 75013'; // Default to Experian
  }
};

// Add the missing storeLetterInStorage function
export const storeLetterInStorage = (letterData: any): boolean => {
  try {
    console.log("Storing letter in storage:", letterData);
    
    // Ensure we have content in both fields for compatibility
    const normalizedLetter = {
      ...letterData,
      content: letterData.content || letterData.letterContent || '',
      letterContent: letterData.letterContent || letterData.content || '',
      id: letterData.id || Date.now(),
      bureau: letterData.bureau || 'Experian',
      createdAt: letterData.createdAt || new Date().toISOString()
    };
    
    // Store the letter
    sessionStorage.setItem('pendingDisputeLetter', JSON.stringify(normalizedLetter));
    
    // Also store in the array format for consistency
    sessionStorage.setItem('generatedDisputeLetters', JSON.stringify([normalizedLetter]));
    
    // Set auto-generated flag
    sessionStorage.setItem('autoGeneratedLetter', 'true');
    
    console.log("Letter successfully stored in session storage");
    return true;
  } catch (error) {
    console.error("Error storing letter in storage:", error);
    return false;
  }
};
