
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnpsiyuwlovbngqzyxlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ucHNpeXV3bG92Ym5ncXp5eGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDE0ODEsImV4cCI6MjA1OTU3NzQ4MX0.dMuHGHCxHsX4ujAoxP4k3GNKuTFFEI5SfT50xWGmmts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
