
/**
 * Utility to fully clear all letter-related data from sessionStorage
 * This is used in multiple places to ensure a clean slate for letter generation
 */

export const clearAllLetterData = (): void => {
  console.log("Clearing ALL letter data from session storage");
  
  // Clear ALL letter-related storage items
  try {
    // Clear letter data
    sessionStorage.removeItem('pendingDisputeLetter');
    sessionStorage.removeItem('generatedDisputeLetters');
    sessionStorage.removeItem('autoGeneratedLetter');
    
    // Clear letter state flags
    sessionStorage.removeItem('hasDisputeLetters');
    sessionStorage.removeItem('forceLettersReload');
    sessionStorage.removeItem('forceLetterGeneration');
    
    // Clear template data
    sessionStorage.removeItem('letterTemplate');
    sessionStorage.removeItem('sampleLetters');
    sessionStorage.removeItem('fallbackLetterUsed');
    
    // Clear navigation flags
    sessionStorage.removeItem('navigationInProgress');
    sessionStorage.removeItem('shouldNavigateToLetters');
    
    console.log("Successfully cleared all letter-related data");
  } catch (error) {
    console.error("Error clearing letter data:", error);
  }
};

/**
 * Check if there's any letter data in session storage
 */
export const hasLetterData = (): boolean => {
  return (
    sessionStorage.getItem('pendingDisputeLetter') !== null ||
    sessionStorage.getItem('generatedDisputeLetters') !== null ||
    sessionStorage.getItem('autoGeneratedLetter') !== null
  );
};
