
/**
 * Utility functions to clear and check letter data in storage
 */

/**
 * Clear all letter-related data from session storage
 * This ensures we don't have any stale letters when creating new ones
 */
export const clearAllLetterData = (): void => {
  console.log("Clearing ALL letter data from storage");
  
  // Remove all possible letter storage keys
  sessionStorage.removeItem('generatedDisputeLetters');
  sessionStorage.removeItem('pendingDisputeLetter');
  sessionStorage.removeItem('autoGeneratedLetter');
  sessionStorage.removeItem('hasDisputeLetters');
  
  // Also remove any flags related to letter generation
  sessionStorage.removeItem('reportReadyForLetters');
  sessionStorage.removeItem('letterGenerationInProgress');
  sessionStorage.removeItem('forceLetterGeneration');
  sessionStorage.removeItem('fallbackLetterUsed');
  
  console.log("All letter data cleared from storage");
};

/**
 * Check if any letter data exists in storage
 */
export const hasLetterData = (): boolean => {
  const generatedLetters = sessionStorage.getItem('generatedDisputeLetters');
  const pendingLetter = sessionStorage.getItem('pendingDisputeLetter');
  const autoLetter = sessionStorage.getItem('autoGeneratedLetter');
  
  return !!(generatedLetters || pendingLetter || autoLetter);
};

/**
 * Force clear all letter data and reload the page
 * This is a nuclear option for when things get stuck
 */
export const forceClearAndReload = (): void => {
  clearAllLetterData();
  sessionStorage.removeItem('creditReportData');
  sessionStorage.removeItem('reportIssues');
  window.location.reload();
};
